Added AWS Credentials Support for Scanning Private Registry
aquasecurity/starboard pull request #1062
Opened 2022-03-23 12:32 UTC by VF-mbrauer

Added support for scanning the **private registry** of AWS-ECR.
Feature still in Beta-mode but usable when prerequisites are met.

**Prerequisite:**
K8S-Kiam or any other method IRSA (Future) to be used to allow Assuming Instance Roles.

**Configurations:**
Annotate the Starboard Namespace to be allowed to use KIAM:
`Annotations:  iam.amazonaws.com/permitted: .*`

Add the Role you want to Assume which has the proper right to create ECR-Credentials
```
podAnnotations: 
    # iam.amazonaws.com/role: <yourRolewithPermissions>
```

Configuration in HELM value file to enable the feature
`trivy.useEcrRoleCreds: false`

2022-03-28 07:06 UTC, chen-keinan requested changes

2022-03-28 07:06 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +				fmt.Println(aerr.Error())
same here use logger

2022-03-28 07:06 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +				fmt.Println(ecr.ErrCodeInvalidParameterException, aerr.Error())
same here use logger

2022-03-28 07:06 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +			fmt.Println(err.Error())
^

2022-03-28 07:06 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +	sDec, _ := base64.StdEncoding.DecodeString(credentials)
`error` should not be ignored

2022-03-28 07:09 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +			var creds (ecr_credentials) = ecr_credentials{aws_creds[0][1], aws_creds[0][2]}
check matrix size both row and column to avoid `index out of bound`

2022-03-28 07:10 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +			var creds (ecr_credentials) = ecr_credentials{aws_creds[0][1], aws_creds[0][2]}
check matrix size both row and column to avoid `index out of range`

2022-04-02 02:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1062) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1062) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/starboard?pullRequest=1062) it.</sub>

2022-04-04 08:29 UTC, VF-mbrauer commented
Due to the new Release 0.15.0 the PR needed to be rebased. For this, a new PR has been created #1103
This PR can be closed.

2022-04-04 08:29 UTC, closed without merging