feat(trivy): Add dbRepository flag to get advisory database from OCI registry
aquasecurity/starboard pull request #1064
Opened 2022-03-23 15:32 UTC by ksashikumar

2022-03-23 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1064) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/starboard?pullRequest=1064) it.</sub>

2022-03-23 16:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1064) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/aquasecurity/starboard?pullRequest=1064) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/aquasecurity/starboard?pullRequest=1064) it.</sub>

2022-03-24 17:47 UTC, ksashikumar commented
@knqyf263 Could you please review this dependent PR also? Thanks 🙂

2022-03-28 06:45 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +	dbRepository, _ := c.GetRequiredData(keyTrivyDBRepository)
err should not be ignored

2022-03-28 06:45 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +func (c Config) GetDBRepository() string {
method should return err as well

2022-03-28 06:45 UTC, chen-keinan commented on pkg/plugin/trivy/plugin.go
> +			keyTrivyDBRepository: "ghcr.io/aquasecurity/trivy-db",
make `ghcr.io/aquasecurity/trivy-db` a const

2022-03-29 14:11 UTC, chen-keinan commented on deploy/helm/values.yaml
> +  dbRepository: "ghcr.io/aquasecurity/trivy-db"
maybe should use this const in tests as well

2022-04-05 06:28 UTC, ksashikumar commented
@chen-keinan Thanks for the comments, I've addressed them 🙂 Could you please take an another look?

2022-04-05 06:33 UTC, chen-keinan commented
> @chen-keinan Thanks for the comments, I've addressed them 🙂 Could you please take an another look?

Thank you for the update; LGTM!!

2022-04-05 13:15 UTC, knqyf263 commented
Note that `--db-repository` was added in v0.25.1, but it had a critical bug. Please use v0.25.2 or greater.

2022-04-05 13:53 UTC, chen-keinan commented
@ksashikumar this PR should also include the trivy version change from : trivy:0.24.2 to trivy:0.25.1 (the version that support `--db-repository` flag)  Its used in various places in the code:
 example: `values.yaml` , `starboard.yaml` etc. (test files)

2022-04-05 17:45 UTC, ksashikumar commented
> @ksashikumar this PR should also include the trivy version change from : `trivy:0.24.2` to `trivy:0.25.2` (the version that support `--db-repository` flag) Its used in various places in the code: example: `values.yaml` , `starboard.yaml` etc. (test files)

@chen-keinan Thanks for that! I've updated the version in the files. Could you please take another look?

2022-04-06 05:41 UTC, chen-keinan commented
@ksashikumar thank you for this effort; LGTM.

2022-04-06 06:07 UTC, ksashikumar commented
> @ksashikumar thank you for this effort; need also to update trivy version on `itest--> matcher.go and matcher_test.go` I think this is the cause for the `Integration tests --> Run integration tests / Starboard CLI` to fail

@chen-keinan Oops, I missed that. Thanks for letting me know. I've fixed that 👍

2022-04-07 11:53 UTC, danielpacak requested changes
I've just run the code in my cluster, following the contributing guide, and I'm getting the following errors:

{"level":"error","ts":1649332073.3865209,"logger":"controller.replicaset","msg":"Reconciler error","reconciler group":"apps","reconciler kind":"ReplicaSet","name":"local-path-provisioner-5ddd94ff66","namespace":"local-path-storage","error":"constructing scan job: property trivy.dbRepository not set","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/Users/dpacak/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/Users/dpacak/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

Please check my comments to see why it may happen. This should also fix integration tests run in the CI workflow.

2022-04-07 11:53 UTC, danielpacak commented on deploy/static/starboard.yaml
> +  trivy.imageRef: "docker.io/aquasec/trivy:0.25.2"
I think we should also add trivy.dbRepository property here, otherwise you'll get errors: `property trivy.dbRepository not set`

2022-04-07 11:53 UTC, danielpacak commented on docs/vulnerability-scanning/trivy.md
> +| `trivy.imageRef`                   | `docker.io/aquasec/trivy:0.25.2`   | Trivy image reference
Please document also this new property trivy.dbRepository.

2022-04-07 11:53 UTC, danielpacak commented on pkg/plugin/trivy/plugin_test.go
> +const defaultDBRepository = "ghcr.io/aquasecurity/trivy-db"
We should set this default value also in static YAMLs

2022-04-08 11:24 UTC, danielpacak approved these changes

2022-04-08 11:25 UTC, merged