chore: add avd_reference to kube-hunter report
aquasecurity/starboard pull request #407
Opened 2021-02-20 03:43 UTC by krol3

Related the issue [395](https://github.com/aquasecurity/starboard/issues/395)
Is it necessary to update the lens and octant plugin too?

2021-03-17 12:24 UTC, danielpacak requested changes
Good job @krol3 I think we just have to rename `avdRefernec` to `avd_reference` so the property is actually persisted in etcd.  Make sure it's the case by running `./bin/starboard scan kubehunterreports` and then inspect the actual report.

2021-03-17 12:24 UTC, danielpacak commented on pkg/apis/aquasecurity/v1alpha1/kube_hunter_types.go
> +														"avdReference":  {Type: "string"},
KubeHunter is using `avd_reference` not `avdReference`. If you provide Open API spec only defined properties are persisted in CRD/etcd.

```suggestion
														"avd_reference":  {Type: "string"},
```

2021-03-17 12:24 UTC, danielpacak commented on deploy/crd/kubehunterreports.crd.yaml
> +                      avdReference:
```suggestion
                      avd_reference:
```

2021-03-17 12:24 UTC, danielpacak commented on deploy/crd/kubehunterreports.crd.yaml
> +                      - avdReference
```suggestion
                      - avd_reference
```

2021-03-18 01:13 UTC, krol3 commented
Hi! @danielpacak  I tested this new version, after the update.

`k get kubehunterreports.aquasecurity.github.io -o yaml | more`

```
    vulnerabilities:
    - avd_reference: https://avd.aquasec.com/kube-hunter/none/
      category: Access Risk
      description: |-
        CAP_NET_RAW is enabled by default for pods.
            If an attacker manages to compromise a pod,
            they could potentially take advantage of this capability to perform network
            attacks on other pods running on the same node
```

2021-03-18 06:47 UTC, danielpacak approved these changes

2021-03-18 06:48 UTC, merged