feat(cli): Show top 5 vulnerabilities by score in html report for namespace
aquasecurity/starboard pull request #463
Opened 2021-03-26 17:39 UTC by xyoxo

Resolves https://github.com/aquasecurity/starboard/issues/459

2021-03-31 13:28 UTC, danielpacak requested changes
👋 Good job @xyoxo I tested on my end and the report looks good. I left few comments and suggestions to look at.

2021-03-31 15:40 UTC, xyoxo commented on pkg/report/templates/types.go
> +	ID                string
I think that'll be better.

2021-03-31 19:14 UTC, xyoxo commented on pkg/plugin/trivy/model.go
> +	V3Score float64 `json:"V3Score,omitempty"`
I think, making it pointer will fix it. Then, if the json output is empty, we'll get nil value instead of 0.0.

2021-04-01 14:11 UTC, danielpacak approved these changes
LGTM!

2021-04-01 14:12 UTC, merged