Introduce resource request/limit parameters for trivy pod
aquasecurity/starboard pull request #639
Opened 2021-07-16 20:29 UTC by elek

This PR solves the problem reported in #572: with for new configuration values the resource/limit requirements of the trivy pod can be adjusted.

Defaults are added to the Helm charts and k8s resources:

```
#k8s resource requests and limits
  resources:
    request:
      cpu: 100m
      memory: 100M
    limit:
      cpu: 500m
      memory: 500M
```

But configmap of existing custom instances should be updated to use limits as before.

2021-07-19 09:10 UTC, danielpacak requested changes
Good work @elek ! I left a few comments but overall code looks good.

Before we can merge it, please make sure that the unit tests are passing. An easy fix would be to add the default resource requests and limits to test fixture:

```go
func TestScanner_GetScanJobSpec(t *testing.T) {

	testCases := []struct {
		name string

		config       map[string]string
		workloadSpec corev1.PodSpec

		expectedSecrets []corev1.Secret
		expectedJobSpec corev1.PodSpec
	}{
		{
			name: "Standalone mode without insecure registry",
			config: map[string]string{
				"trivy.imageRef": "docker.io/aquasec/trivy:0.14.0",
				"trivy.mode":     string(trivy.Standalone),

				"trivy.resources.request.cpu":    "100m",
				"trivy.resources.request.memory": "100M",
				"trivy.resources.limit.cpu":      "500m",
				"trivy.resources.limit.memory":   "500M",
```

2021-07-19 09:10 UTC, danielpacak commented on pkg/plugin/trivy/plugin.go
> -var (
For backward compatibility we should add requests and limits to the Init callback, which is used to ensure the default config for a plugin:

```go
// Init ensures the default Config required by this plugin.
func (p *plugin) Init(ctx starboard.PluginContext) error {
	return ctx.EnsureConfig(starboard.PluginConfig{
		Data: map[string]string{
			keyTrivyImageRef: "docker.io/aquasec/trivy:0.16.0",
			keyTrivySeverity: "UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL",
			keyTrivyMode:     string(Standalone),

			"trivy.resources.request.cpu":    "100m",
			"trivy.resources.request.memory": "100M",
			"trivy.resources.limit.cpu":      "500m",
			"trivy.resources.limit.memory":   "500M",
		},
	})
}
```

It is also used by Starboard CLI in pkg/cmd/installer.go

2021-07-19 09:10 UTC, danielpacak commented on pkg/plugin/trivy/plugin_test.go
> +func TestConfig_GetResourceResourceRequirements(t *testing.T) {
```suggestion
func TestConfig_GetResourceRequirements(t *testing.T) {
```

2021-07-19 19:51 UTC, elek commented
Thanks the suggestion @danielpacak. I improved the error handling and defaults handling.

Still, one test is failing locally:

```
• Failure [6.160 seconds]
Starboard CLI
/home/elek/s/starboard/itest/starboard/starboard_cli_test.go:34
  Command init
  /home/elek/s/starboard/itest/starboard/starboard_cli_test.go:44
    should initialize Starboard [It]
    /home/elek/s/starboard/itest/starboard/starboard_cli_test.go:46
```

But the same test is also failing (locally) on my `origin/main`. As all the other tests are passing, I think it can be tested on the CI while I am debugging my local environments...

2021-07-20 07:09 UTC, danielpacak requested changes

2021-07-21 06:45 UTC, elek commented on deploy/static/05-starboard-operator.config.yaml
> +  trivy.resources.limit.cpu: 500M
Yes, I realized in the test but it should be fixed in the last commit, let me check...

2021-07-21 21:33 UTC, elek commented on deploy/static/05-starboard-operator.config.yaml
> +  trivy.resources.limit.cpu: 500M
Oh, no. I did the same mistake in `plugin.go` but that one is catched by the unit tests. I guess the static files are not covered by them. Thanks to point to it.

2021-07-23 08:13 UTC, danielpacak approved these changes

2021-07-23 08:31 UTC, merged