chore: documentation getting started
aquasecurity/starboard pull request #750
Opened 2021-10-15 02:54 UTC by krol3

Improving the copy and paste console, and using results table for the results.

2022-01-03 20:33 UTC, krol3 commented
Hi @danielpacak , I tried to follow the same approach about trivy documentation. 
Using in the markdown the details and summary. Any improvement or comment about this? 

<details>
<summary>Result</summary>

2022-01-06 17:26 UTC, danielpacak commented
> Hi @danielpacak , I tried to follow the same approach about trivy documentation. Using in the markdown the details and summary. Any improvement or comment about this?
> 
> Result

I know the `<details>` and `<summary>` tags. But personally, I don't really like it because when you print the documentation page (e.g. to PDF) the layout and highlight is broken. For the the MkDocs should fix the copy experience when you use console as code block language.

<pre>
```console
$ only the line prefixed with the dollar sign should be copied
output of the command
output of the command
```
</pre>
```console
$ name -a
Darwin dpacak-imac.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64
```

 Anyway, I let @chen-keinan decide if we want to use it.

2022-01-09 15:04 UTC, chen-keinan commented
I agree that this PR in a way is kind of a workaround to the problem; however I feel we should go with it because:
- It solves the problem - shell commands only copied
- It makes the docs look clean
- Its look and feel is similar to Trivy (which is important for our open source docs to look alike)

2022-01-11 09:06 UTC, danielpacak requested changes
Before we merge this one please see my comment about labels and implementation details. Otherwise I'm okey with details and summary tags.

2022-01-11 09:06 UTC, danielpacak commented on docs/cli/getting-started.md
> +kubectl get configauditreport -o wide \
We no longer recommend using kubectl get configauditrepors as the naming convention and label selectors might change. In other works labels set is an implementation details. Also for some K8s object, that contain semicolons we cannot use labels and we fallback to annotations. See the code for details.

2022-01-18 12:31 UTC, danielpacak approved these changes

2022-01-18 12:32 UTC, merged